version: '3.7'

services:
  bot:
    restart: on-failure
    build: .
    container_name: sucrilhos_bot
    volumes:
      - "./:/usr/src"
    command: "python3 ./src/beta-sucribot.py sucrilhos_bot"

volumes:
  deps:
