
def send_welcome(bot, message):
    print("got vtncp!")
    s = """................./¯/)...................
................/¯ ./....................
............../. . /......................
......./´¯/ . . /´¯•,...................
..../' /. / . ./ ../'.¯\................
..( . ( . ( . ( ¯ .\ . ')...............
...\ . . . . . . . . . . ./................
.....\ . . . . . . . . ./..................
.....(. . . . . . . . . \..................
VAI TOMA NO CU PUERA"""

    bot.send_message(message.chat.id, s)
    
def send_help(bot, message, i):
    verse = ['I need somebody', 'not just anybody', 'you know I need someone', 'HELP!']
    bot.send_message(message.chat.id, verse[i%len(verse)])
    
